## Clinical Data Preprocessing
Steps include:
1. Clinical Data Audit / Report
2. Handle missing values
3. Remove bad features (e.g. features with too many missing values, or features that are not relevant for the analysis)
4. Handle outliers (e.g. using IQR method, Z-score method)
5. ...
6. Export processed dataset

In [16]:
import src.reporting as r
print(dir(r))

['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '__warningregistry__', 'clinical_data_audit', 'data_quality_report', 'display', 'extract_dtypes', 'np', 'pd']

## Add common imports
From /src/01_common_imports.py and from other relevant /src/ files

In [18]:
from src.common_imports import *
import importlib
import src.reporting as rp
importlib.reload(rp)
from src.reporting import clinical_data_audit, low_variance_report
from src.load_data import load_all_sheets

## Load All Sheets

In [2]:
data = load_all_sheets()

Loading clinical...
Loading protogen...
Loading somascan...
Done loading

## Clinical Data Audit / Report per DataFrame
df_clinical

In [6]:
df_clinical = data["df_clinical"]
clinical_data_audit(df_clinical, name="dataset")

======================================================================
CLINICAL AUDIT: DATASET
======================================================================

1. STRUCTURE
Shape: 327 rows × 67 columns

2. DUPLICATES
Duplicate rows: 0

3. MISSING VALUES

Columns > 40% missing (likely drop):

                             missing_count  missing_pct
Hep B serology wk 9 (IU/mL)            294     0.899083
vaccine centre                         275     0.840979

Moderate missing values (likely impute):

                    missing_count  missing_pct
FinalxRAYScore                 92     0.281346
InitialxRAYScore               55     0.168196
Erosive                        55     0.168196
Remission month                54     0.165138
HighDisease(>4DAS)             54     0.165138
Remission(<2.6DAS)             54     0.165138
CRP.9M                         53     0.162080
ACPA.POSITIVE                  52     0.159021
TOTAL.SWOLLEN.9M               52     0.159021
TOTAL.TENDER.9M                52     0.159021
EOSINOPHILS.0M                 52     0.159021
DAS28.6M                       52     0.159021
BASOPHILS.6M                   52     0.159021
CRP.6M                         52     0.159021
DAS28.3M                       52     0.159021

4. NUMERIC FEATURES
Numeric columns: 3

Top features by outliers:

            count      mean       std  min  25%  50%  75%   max  outliers_iqr
Region      275.0  4.403636  3.341946  1.0  1.0  3.0  7.0  10.0             0
Hub         275.0  3.454545  1.866123  1.0  2.0  3.0  5.0   7.0             0
REGION_HUB  275.0  6.083636  3.521092  1.0  3.0  6.0  8.0  12.0             0

5. CATEGORICAL CONSISTENCY
Columns with inconsistent casing: ['Patient_ID', 'Digest', 'Study', 'IM.STEROIDS.3MONTHS', 'ACPA.POSITIVE', 'RHUEMATOID.FACTOR', 'DAS28.0M', 'DAS28.3M', 'DAS28.6M', 'DAS28.9M', 'DAS28.12M', 'DAS28.18M', 'Remission month', 'Remission(<2.6DAS)', 'HighDisease(>4DAS)', 'Symp_Duration', 'HAQ.0M', 'HAQ.6M', 'SDAI.0M', 'SDAI.6M', 'SDAI.12M', 'BASOPHILS.0M', 'EOSINOPHILS.0M', 'HB.0M', 'LYMPHOCYTES.0M', 'MONOCYTES.0M', 'NEUTROPHILS.0M', 'PLT.0M', 'WBC.0M', 'CRP.0M', 'ESR.0M', 'FATIQUE.0M', 'PAIN.0M', 'TOTAL.SWOLLEN.0M', 'TOTAL.TENDER.0M', 'BASOPHILS.6M', 'EOSINOPHILS.6M', 'HB.6M', 'LYMPHOCYTES.6M', 'MONOCYTES.6M', 'NEUTROPHILS.6M', 'PLT.6M', 'WBC.6M', 'CRP.6M', 'FATIQUE.6M', 'PAIN.6M', 'TOTAL.SWOLLEN.6M', 'TOTAL.TENDER.6M', 'CRP.9M', 'TOTAL.SWOLLEN.9M', 'TOTAL.TENDER.9M', 'ORAL.STEROIDS.3M', 'AGE', 'RACE', 'GENDER', 'HEIGHT', 'WEIGHT', 'ALCOHOL_Y_N', 'CURENT SMOKER', 'InitialxRAYScore', 'FinalxRAYScore', 'Erosive', 'Hep B serology wk 9 (IU/mL)', 'vaccine centre']

6. CLEANING SUMMARY
- High missing (> 40%): 2
- Moderate missing: 57
- Numeric features: 3

======================================================================

{'high_missing':                              missing_count  missing_pct
 Hep B serology wk 9 (IU/mL)            294     0.899083
 vaccine centre                         275     0.840979,
 'mid_missing':                      missing_count  missing_pct
 FinalxRAYScore                  92     0.281346
 InitialxRAYScore                55     0.168196
 Erosive                         55     0.168196
 Remission month                 54     0.165138
 HighDisease(>4DAS)              54     0.165138
 Remission(<2.6DAS)              54     0.165138
 CRP.9M                          53     0.162080
 ACPA.POSITIVE                   52     0.159021
 TOTAL.SWOLLEN.9M                52     0.159021
 TOTAL.TENDER.9M                 52     0.159021
 EOSINOPHILS.0M                  52     0.159021
 DAS28.6M                        52     0.159021
 BASOPHILS.6M                    52     0.159021
 CRP.6M                          52     0.159021
 DAS28.3M                        52     0.159021
 CRP.0M                          52     0.159021
 BASOPHILS.0M                    52     0.159021
 LYMPHOCYTES.0M                  52     0.159021
 HB.0M                           52     0.159021
 EOSINOPHILS.6M                  52     0.159021
 ESR.0M                          52     0.159021
 DAS28.9M                        52     0.159021
 HAQ.0M                          52     0.159021
 FATIQUE.0M                      52     0.159021
 FATIQUE.6M                      52     0.159021
 Hub                             52     0.159021
 HB.6M                           52     0.159021
 HAQ.6M                          52     0.159021
 NEUTROPHILS.6M                  52     0.159021
 LYMPHOCYTES.6M                  52     0.159021
 DAS28.0M                        52     0.159021
 DAS28.12M                       52     0.159021
 DAS28.18M                       52     0.159021
 WBC.6M                          52     0.159021
 WBC.0M                          52     0.159021
 SDAI.12M                        52     0.159021
 SDAI.0M                         52     0.159021
 Symp_Duration                   52     0.159021
 ORAL.STEROIDS.3M                52     0.159021
 MONOCYTES.6M                    52     0.159021
 MONOCYTES.0M                    52     0.159021
 PAIN.6M                         52     0.159021
 PLT.0M                          52     0.159021
 REGION_HUB                      52     0.159021
 PLT.6M                          52     0.159021
 RHUEMATOID.FACTOR               52     0.159021
 Region                          52     0.159021
 PAIN.0M                         52     0.159021
 NEUTROPHILS.0M                  52     0.159021
 TOTAL.SWOLLEN.6M                52     0.159021
 TOTAL.SWOLLEN.0M                52     0.159021
 TOTAL.TENDER.6M                 52     0.159021
 TOTAL.TENDER.0M                 52     0.159021
 SDAI.6M                         52     0.159021
 IM.STEROIDS.3MONTHS             51     0.155963
 HEIGHT                           7     0.021407
 Digest                           3     0.009174}

df_steroids

In [7]:
df_steroids = data["df_steroids"]
clinical_data_audit(df_steroids, name="dataset")

======================================================================
CLINICAL AUDIT: DATASET
======================================================================

1. STRUCTURE
Shape: 414 rows × 10 columns

2. DUPLICATES
Duplicate rows: 0

3. MISSING VALUES

Columns > 40% missing (likely drop):

Empty DataFrame
Columns: [missing_count, missing_pct]
Index: []

Moderate missing values (likely impute):

                    missing_count  missing_pct
Date of Assessment              2     0.004831

4. NUMERIC FEATURES
Numeric columns: 4

Top features by outliers:

,count,mean,std,min,25%,50%,75%,max,outliers_iqr
Joint Injected,414.0,17.495169,3.959080,3.0,19.0,19.0,19.0,29.0,93
Dose,414.0,100.454831,73.450490,-99.0,80.0,120.0,120.0,1000.0,9
Unit,414.0,1.009662,0.120143,1.0,1.0,1.0,1.0,3.0,3
Assessment,414.0,6.371981,4.282041,3.0,3.0,6.0,9.0,19.0,1

5. CATEGORICAL CONSISTENCY
Columns with inconsistent casing: ['Digest', '4. Has the patient received a steroid injection?', 'Steroid', 'Route']

6. CLEANING SUMMARY
- High missing (> 40%): 0
- Moderate missing: 1
- Numeric features: 4

======================================================================

{'high_missing': Empty DataFrame
 Columns: [missing_count, missing_pct]
 Index: [],
 'mid_missing':                     missing_count  missing_pct
 Date of Assessment              2     0.004831}

df_meds

In [8]:
df_meds = data["df_meds"]
clinical_data_audit(df_meds, name="dataset")

======================================================================
CLINICAL AUDIT: DATASET
======================================================================

1. STRUCTURE
Shape: 2534 rows × 9 columns

2. DUPLICATES
Duplicate rows: 0

3. MISSING VALUES

Columns > 40% missing (likely drop):

Empty DataFrame
Columns: [missing_count, missing_pct]
Index: []

Moderate missing values (likely impute):

                    missing_count  missing_pct
Dose                            6     0.002368
Route                           6     0.002368
Frequency                       6     0.002368
Date of Assessment              5     0.001973

4. NUMERIC FEATURES
Numeric columns: 3

Top features by outliers:

,count,mean,std,min,25%,50%,75%,max,outliers_iqr
Dose,2528.0,126.882516,258.375293,1.0,5.0,20.0,200.0,2500.0,156
Unit,2534.0,1.004736,0.097224,1.0,1.0,1.0,1.0,3.0,6
Assessment,2534.0,8.838595,4.910288,3.0,6.0,9.0,12.0,19.0,0

5. CATEGORICAL CONSISTENCY
Columns with inconsistent casing: ['Digest', 'RA Medication', 'Frequency', 'Route']

6. CLEANING SUMMARY
- High missing (> 40%): 0
- Moderate missing: 4
- Numeric features: 3

======================================================================

{'high_missing': Empty DataFrame
 Columns: [missing_count, missing_pct]
 Index: [],
 'mid_missing':                     missing_count  missing_pct
 Dose                            6     0.002368
 Route                           6     0.002368
 Frequency                       6     0.002368
 Date of Assessment              5     0.001973}

## Clinical Low Variance Audit / Report per DataFrame
df_clinical

In [19]:
low_variance_report(df_clinical, name="dataset")

===== LOW VARIANCE REPORT: DATASET =====

Total numeric features: 3
Low variance threshold: 0.01
Low variance features found: 0

No low-variance features detected.

{'low_variance_features': Series([], dtype: float64),
 'variance': Hub            3.482415
 Region        11.168600
 REGION_HUB    12.398089
 dtype: float64,
 'drop_columns': []}

df_steroids

In [20]:
low_variance_report(df_steroids, name="dataset")

===== LOW VARIANCE REPORT: DATASET =====

Total numeric features: 4
Low variance threshold: 0.01
Low variance features found: 0

No low-variance features detected.

{'low_variance_features': Series([], dtype: float64),
 'variance': Unit                 0.014434
 Joint Injected      15.674311
 Assessment          18.335872
 Dose              5394.974444
 dtype: float64,
 'drop_columns': []}

df_meds

In [21]:
low_variance_report(df_meds, name="dataset")

===== LOW VARIANCE REPORT: DATASET =====

Total numeric features: 3
Low variance threshold: 0.01
Low variance features found: 1

Top low-variance features:
Unit    0.009452
dtype: float64

{'low_variance_features': Unit    0.009452
 dtype: float64,
 'variance': Unit              0.009452
 Assessment       24.110930
 Dose          66757.792286
 dtype: float64,
 'drop_columns': ['Unit']}